# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Googleの日本語フォント # Google Fonts Japanese
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: googlefonts
github_username:  googlefonts
exclude: ['node_modules']

# “Not everything is a post or a page.” Rather than use posts, these are the type
# specimen sections.
collections:
  specimens:
    output: false # No individual specimen pages
    permalink: /specimens/:path/
    default:
      layout: none

# TODO Set default layout and other metadata
# per https://jekyllrb.com/docs/collections/

# Build settings
markdown: kramdown
browserify:
  exts: [".js"] # Target extensions
  command: "browserify -" # Use Browserify in `node_modules`
autoprefixer:
  browsers:
    - "> 1%"
    - "last 2 versions"
    - "iOS >= 6"

# theme: ./
