runtime: python27
api_version: 1
threadsafe: yes

error_handlers:
- file: 404.html

handlers:
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: \1
  upload: (.*\.(appcache|manifest))
  expiration: "0m"
  application_readable: true

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: \1
  upload: (.*\.atom)
  expiration: "1h"
  application_readable: true

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: \1
  upload: (.*\.crx)
  application_readable: true

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)
  application_readable: true

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: \1
  upload: (.*\.eot)
  application_readable: true

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: \1
  upload: (.*\.htc)
  application_readable: true

- url: /(.*\.html)
  # upload: (.*\.html)
  script: auth.application

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: \1
  upload: (.*\.ico)
  expiration: "7d"
  application_readable: true

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)
  application_readable: true

- url: /(.*\.json)
  mime_type: application/json
  static_files: \1
  upload: (.*\.json)
  expiration: "1h"
  application_readable: true

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: \1
  upload: (.*\.m4v)
  application_readable: true

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: \1
  upload: (.*\.mp4)
  application_readable: true

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: \1
  upload: (.*\.(ogg|oga))
  application_readable: true

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: \1
  upload: (.*\.ogv)
  application_readable: true

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: \1
  upload: (.*\.otf)
  application_readable: true

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: \1
  upload: (.*\.rss)
  expiration: "1h"
  application_readable: true

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: \1
  upload: (.*\.safariextz)
  application_readable: true

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: \1
  upload: (.*\.(svg|svgz))
  application_readable: true

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: \1
  upload: (.*\.swf)
  application_readable: true

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: \1
  upload: (.*\.ttf)
  application_readable: true

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)
  application_readable: true

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  static_files: \1
  upload: (.*\.unity3d)
  application_readable: true

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: \1
  upload: (.*\.webm)
  application_readable: true

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: \1
  upload: (.*\.webp)
  application_readable: true

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: \1
  upload: (.*\.woff)
  application_readable: true

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)
  expiration: "1h"
  application_readable: true

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: \1
  upload: (.*\.xpi)
  application_readable: true

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))
  application_readable: true

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: \1
  upload: (.*\.(mid|midi|mp3|wav))
  application_readable: true

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: \1
  upload: (.*\.(doc|exe|ppt|rtf|xls))
  application_readable: true

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: \1
  upload: (.*\.(bz2|gz|rar|tar|tgz|zip))
  application_readable: true



# index files
- url: /(.+)/
  script: auth.application

- url: /(.+)
  script: auth.application

# - url: /(.+)/
#   static_files: \1/index.html
#   upload: (.+)/index.html
#   expiration: "15m"
#   application_readable: true
#
# - url: /(.+)
#   static_files: \1/index.html
#   upload: (.+)/index.html
#   expiration: "15m"
#   application_readable: true
